// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc/entity/mob.proto

package entity_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exp     float32 `protobuf:"fixed32,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Attack  float32 `protobuf:"fixed32,4,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense float32 `protobuf:"fixed32,5,opt,name=defense,proto3" json:"defense,omitempty"`
}

func (x *Mob) Reset() {
	*x = Mob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_entity_mob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mob) ProtoMessage() {}

func (x *Mob) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_entity_mob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mob.ProtoReflect.Descriptor instead.
func (*Mob) Descriptor() ([]byte, []int) {
	return file_grpc_entity_mob_proto_rawDescGZIP(), []int{0}
}

func (x *Mob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mob) GetExp() float32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Mob) GetAttack() float32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *Mob) GetDefense() float32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

type CreateMobDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exp     float32 `protobuf:"fixed32,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Attack  float32 `protobuf:"fixed32,4,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense float32 `protobuf:"fixed32,5,opt,name=defense,proto3" json:"defense,omitempty"`
}

func (x *CreateMobDto) Reset() {
	*x = CreateMobDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_entity_mob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMobDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMobDto) ProtoMessage() {}

func (x *CreateMobDto) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_entity_mob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMobDto.ProtoReflect.Descriptor instead.
func (*CreateMobDto) Descriptor() ([]byte, []int) {
	return file_grpc_entity_mob_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMobDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMobDto) GetExp() float32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *CreateMobDto) GetAttack() float32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *CreateMobDto) GetDefense() float32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

type MobBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exp     float32 `protobuf:"fixed32,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Attack  float32 `protobuf:"fixed32,4,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense float32 `protobuf:"fixed32,5,opt,name=defense,proto3" json:"defense,omitempty"`
}

func (x *MobBase) Reset() {
	*x = MobBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_entity_mob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MobBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobBase) ProtoMessage() {}

func (x *MobBase) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_entity_mob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobBase.ProtoReflect.Descriptor instead.
func (*MobBase) Descriptor() ([]byte, []int) {
	return file_grpc_entity_mob_proto_rawDescGZIP(), []int{2}
}

func (x *MobBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MobBase) GetExp() float32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *MobBase) GetAttack() float32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *MobBase) GetDefense() float32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

type GetMobsRequestDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GetMobsRequestDto) Reset() {
	*x = GetMobsRequestDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_entity_mob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMobsRequestDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMobsRequestDto) ProtoMessage() {}

func (x *GetMobsRequestDto) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_entity_mob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMobsRequestDto.ProtoReflect.Descriptor instead.
func (*GetMobsRequestDto) Descriptor() ([]byte, []int) {
	return file_grpc_entity_mob_proto_rawDescGZIP(), []int{3}
}

func (x *GetMobsRequestDto) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMobsRequestDto) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ReceiveMobsDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobs     []*Mob `protobuf:"bytes,1,rep,name=mobs,proto3" json:"mobs,omitempty"`
	Page     int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Count    int64  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReceiveMobsDto) Reset() {
	*x = ReceiveMobsDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_entity_mob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveMobsDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMobsDto) ProtoMessage() {}

func (x *ReceiveMobsDto) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_entity_mob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMobsDto.ProtoReflect.Descriptor instead.
func (*ReceiveMobsDto) Descriptor() ([]byte, []int) {
	return file_grpc_entity_mob_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveMobsDto) GetMobs() []*Mob {
	if x != nil {
		return x.Mobs
	}
	return nil
}

func (x *ReceiveMobsDto) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReceiveMobsDto) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReceiveMobsDto) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_grpc_entity_mob_proto protoreflect.FileDescriptor

var file_grpc_entity_mob_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6d, 0x6f,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x6d, 0x0a, 0x03, 0x4d, 0x6f, 0x62, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x65, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64,
	0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x22, 0x66, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x62, 0x44, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x22, 0x61,
	0x0a, 0x07, 0x4d, 0x6f, 0x62, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e,
	0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73,
	0x65, 0x22, 0x43, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x7f, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4d, 0x6f, 0x62, 0x73, 0x44, 0x74, 0x6f, 0x12, 0x27, 0x0a, 0x04, 0x6d, 0x6f, 0x62, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x62, 0x52, 0x04, 0x6d, 0x6f, 0x62,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x9a, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x62, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x62, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x62, 0x44, 0x74,
	0x6f, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x62, 0x12, 0x4c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x62,
	0x73, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x74, 0x6f, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x6f, 0x62,
	0x73, 0x44, 0x74, 0x6f, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x2d, 0x6c, 0x69, 0x66, 0x65,
	0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2d, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_entity_mob_proto_rawDescOnce sync.Once
	file_grpc_entity_mob_proto_rawDescData = file_grpc_entity_mob_proto_rawDesc
)

func file_grpc_entity_mob_proto_rawDescGZIP() []byte {
	file_grpc_entity_mob_proto_rawDescOnce.Do(func() {
		file_grpc_entity_mob_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_entity_mob_proto_rawDescData)
	})
	return file_grpc_entity_mob_proto_rawDescData
}

var file_grpc_entity_mob_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_entity_mob_proto_goTypes = []interface{}{
	(*Mob)(nil),               // 0: grpc.entity.v1.Mob
	(*CreateMobDto)(nil),      // 1: grpc.entity.v1.CreateMobDto
	(*MobBase)(nil),           // 2: grpc.entity.v1.MobBase
	(*GetMobsRequestDto)(nil), // 3: grpc.entity.v1.GetMobsRequestDto
	(*ReceiveMobsDto)(nil),    // 4: grpc.entity.v1.ReceiveMobsDto
}
var file_grpc_entity_mob_proto_depIdxs = []int32{
	0, // 0: grpc.entity.v1.ReceiveMobsDto.mobs:type_name -> grpc.entity.v1.Mob
	1, // 1: grpc.entity.v1.MobService.CreateMob:input_type -> grpc.entity.v1.CreateMobDto
	3, // 2: grpc.entity.v1.MobService.GetMobs:input_type -> grpc.entity.v1.GetMobsRequestDto
	0, // 3: grpc.entity.v1.MobService.CreateMob:output_type -> grpc.entity.v1.Mob
	4, // 4: grpc.entity.v1.MobService.GetMobs:output_type -> grpc.entity.v1.ReceiveMobsDto
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_entity_mob_proto_init() }
func file_grpc_entity_mob_proto_init() {
	if File_grpc_entity_mob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_entity_mob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_entity_mob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMobDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_entity_mob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MobBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_entity_mob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMobsRequestDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_entity_mob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveMobsDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_entity_mob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_entity_mob_proto_goTypes,
		DependencyIndexes: file_grpc_entity_mob_proto_depIdxs,
		MessageInfos:      file_grpc_entity_mob_proto_msgTypes,
	}.Build()
	File_grpc_entity_mob_proto = out.File
	file_grpc_entity_mob_proto_rawDesc = nil
	file_grpc_entity_mob_proto_goTypes = nil
	file_grpc_entity_mob_proto_depIdxs = nil
}
